name: instamanip
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip:
      - accelerate==1.0.1
      - braceexpand==0.1.7
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - deepspeed==0.15.2
      - diffusers==0.25.0
      - einops==0.8.0
      - huggingface-hub==0.25.2
      - hydra-core==1.3.2
      - numpy==1.26.4
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - peft==0.13.2
      - pillow==11.0.0
      - pyrootutils==1.0.4
      - sentencepiece==0.2.0
      - torch==2.4.1
      - torchdata==0.7.1
      - torchmetrics==1.5.1
      - torchmetrics[image]
      - torchvision==0.19.1
      - tqdm==4.66.5
      - transformers==4.30.2
      - transformers-stream-generator==0.0.5
      - wandb==0.18.3
      - xformers==0.0.28.post3
